version: '3.9'

networks:
  loki:

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: defaultsecret
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    
  gpt4free:
    image: hlohaus789/g4f:latest
    ports:
      - '8080:8080'
      - '1337:1337'
      - '7900:7900'
  
  nats:
    image: nats
    ports:
      - "8222:8222"
      - '6222:6222'
      - '4222:4222'
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
